version: "3.8"

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    ports:
      - "${WEBUI_PORT:-3000}:8080"
    volumes:
      - open_webui_volume:/app/backend/data
    depends_on:
      - searxng
    restart: always
    networks:
      - eudai_net

  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    ports:
      - "${SEARXNG_PORT:-8888}:8080"
    volumes:
      - searxng_volume:/etc/searxng
    restart: always
    networks:
      - eudai_net

volumes:
  open_webui_volume:
  searxng_volume:

networks:
  eudai_net:
    driver: bridge
